config/routes.rb
Rails.application.routes.draw do

  devise_for :coders
  get 'welcome/index'
  resources :codes

  authenticated :coder do
    root 'welcome#welcome', as: "authenticated_root"
  end

  root 'welcome#index'

  get 'welcome' => 'welcome#welcome'
  get 'html/exercise1' => 'html#exercise1'
  get 'css/exercise1' => 'css#exercise1'
  get 'javascript/exercise1' => 'javascript#exercise1'
  get 'ruby/exercise1' => 'ruby#exercise1'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :codes
end

app/models/code.rb
class Code < ActiveRecord::Base
	belongs_to :coder
	belongs_to :category
	validates_presence_of :content
	validates_presence_of :title
	validates_presence_of :category_id
end

app/models/coder.rb
class Coder < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :codes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  # for devise start
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
        end
   # for devise end

end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

	before_action :find_code, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_coder!, only: [:show, :edit, :update, :destroy]
	before_action :add_coder, only: [:edit, :index, :new, :show]

	def index
		# @codes = Code.all.order("created_at DESC")
		# @codes = Code.where(coder_id: current_coder).order("created_at DESC")

		# for categories
		if params[:category].blank?
			@codes = Code.where(coder_id: current_coder).order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@codes = Code.where(category_id: @category_id, coder_id: current_coder).order("created_at DESC")
		end

	end

	def show
	end

	def new
		# @code = Code.new
		if coder_signed_in?
			@code = current_coder.codes.build
		else
			redirect_to new_coder_registration_path
		end
	end

	def create
		# @code = Code.new(code_params)
		@code = current_coder.codes.build(code_params)
		# byebug
		if @code.save
			redirect_to @code
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @code.update(code_params)
			redirect_to @code
		else
			render 'edit'
		end
	end

	def destroy
		@code.destroy
		redirect_to codes_path
	end

	private

		def find_code
			@code = Code.find(params[:id])
		end

		def code_params
			params.require(:code).permit(:title, :content, :category_id)
		end

		def add_coder
			if coder_signed_in?
				@coder = Coder.find(current_coder)
			else
				redirect_to new_coder_registration_path
			end
		end

end

app/controllers/css_controller.rb
class CssController < ApplicationController

	before_action :add_coder, only: [:exercise1]

	private

		def add_coder
			if coder_signed_in?
				@coder = Coder.find(current_coder)
			else
				redirect_to new_coder_session_path
			end
		end	
	
end

app/controllers/html_controller.rb
class HtmlController < ApplicationController
	
	before_action :add_coder, only: [:exercise1]

	private

		def add_coder
			if coder_signed_in?
				@coder = Coder.find(current_coder)
			else
				redirect_to new_coder_session_path
			end
		end	
end

app/controllers/javascript_controller.rb
class JavascriptController < ApplicationController

	before_action :add_coder, only: [:exercise1]

	private

		def add_coder
			if coder_signed_in?
				@coder = Coder.find(current_coder)
			else
				redirect_to new_coder_session_path
			end
		end
	
end

app/controllers/ruby_controller.rb
class RubyController < ApplicationController

	before_action :add_coder, only: [:exercise1]

	private

		def add_coder
			if coder_signed_in?
				@coder = Coder.find(current_coder)
			else
				redirect_to new_coder_session_path
			end
		end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

	def welcome
		if coder_signed_in?
			@coder = Coder.find(current_coder)
		else
			redirect_to new_coder_session_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper

	# def simple_format(text, html_options={}, options={})
	#   start_tag = '<code><pre>'
	#   # text = text.to_s.dup
	#   text.gsub!(/\r\n?/, "\n")                    # \r\n and \r -> \n
	#   text.gsub!(/\n\n+/, "</p>\n\n#{start_tag}")  # 2+ newline  -> paragraph
	#   text.gsub!(/([^\n]\n)(?=[^\n])/, '\1<br />') # 1 newline   -> br
	#   text.insert 0, start_tag
	#   text << "</pre></code>"
	# end
	
end

app/helpers/css_helper.rb
module CssHelper
end

app/helpers/html_helper.rb
module HtmlHelper
end

app/helpers/javascript_helper.rb
module JavascriptHelper
end

app/helpers/ruby_helper.rb
module RubyHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/codes/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="form-css">
				<%= simple_form_for @code do |f| %>
					<%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category" }, class: "form-control", id: "select" %>
					<%= f.input :title, label: "Description" %>
					<%= f.input :content, label: "Code", class: "code_content"%>
					<%= f.button :submit, class: "btn btn-success btn-md" %>&nbsp;&nbsp;&nbsp;
					<%= link_to "Cancel", codes_path, class: "btn btn-danger btn-md" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/codes/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>Edit Your Code</h1>
			<%= render 'form' %>
			<%#= link_to "Cancel", code_path %>
		</div>
	</div>
</div>

app/views/codes/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<br>
			<% unless @codes.blank? %>
				<div style="text-align: center;">
					<% Category.all.each do |category| %>
	  					<%= link_to category.name, codes_path(category: category.name), class: "btn btn-primary btn-sm" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	  				<% end %>
  				</div>

  				<br>

				<% @codes.each do |code| %>
					<div id="codes">
						<h2><%= link_to code.title, code %></h2>
						<p>
							<%= Category.find(code.category_id).name %><br>
							<!-- Modified: <%= time_ago_in_words(code.updated_at) %> ago<br>
							Created: <%= time_ago_in_words(code.created_at) %> ago -->
						</p>
					</div>
				<% end %>
			<% else %>
				<h2>Add Code</h2>
				<p>It appears you haven't created any codes yet... Why don't you create one now?</p>
				<%= link_to "New Code", new_code_path, class: "btn btn-primary btn-lg" %>
			<% end %>
		</div>
	</div>
</div>

app/views/codes/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>Add New Code</h1>
			<%= render 'form' %>
			<%#= link_to "Cancel", codes_path, class: "btn btn-danger btn-md" %>
		</div>
	</div>
</div>

app/views/codes/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div id="code_show">
				<p class="notice"><%= notice %></p>
  				<p class="alert"><%= alert %></p>

				<h1><%= @code.title %></h1>
				<!-- <p><%#= simple_format(@code.content) %></p> -->
				<!-- textarea should be one line with ruby code to show properly -->
				<textarea rows="20" cols="100" readonly class="textareashow"><%= @code.content %></textarea>
				<br><br>
				<div class="btn-show">
					<%= link_to "Edit Code", edit_code_path(@code), class: "btn btn-primary btn-md" %>&nbsp;&nbsp;&nbsp;
					<%= link_to "Delete Code", code_path(@code), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-md" %>&nbsp;&nbsp;&nbsp;
					<%= link_to "My Codes", codes_path, class: "btn btn-success btn-md" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/css/exercise1.html.erb
<div class="container" id="container-body">
	<div class="row">
		<div class="col-md-12">
			<h1>CSS - Exercise 1</h1>
			<p class="lead">Complete a simple css code by dragging the blue boxes to the gray panels.</p>

			<div class="modal" id="myModal">
				<div class="modal-dialog">
					<div class="modal-content" id="welldone">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
							<h4 class="modal-title">Well done, <%= "#{@coder.first_name}" %>!</h4>
						</div>
						<div class="modal-body" id="welldonetext">
							<p>You are now ready to go to the next exercise!</p>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Check your code</button>
							<%= link_to "Next Exercise", javascript_exercise1_path, class: "btn btn-success" %>
						</div>
					</div>
				</div>
			</div>

			<div class="modal" id="myModal2">
				<div class="modal-dialog">
					<div class="modal-content" id="tryagain">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
							<h4 class="modal-title">Almost there, <%= "#{@coder.first_name}" %>!</h4>
						</div>
						<div class="modal-body">
							<p>Tip: Relax and focus. You can do this!</p>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-danger" data-dismiss="modal">Try Again</button>
						</div>
					</div>
				</div>
			</div>
			
		</div> <!-- col -->
	</div> <!-- row  -->
	<div class="row">
		<div class="col-md-12">
			
			<div style="float:left">
			    <div class="square-css" id="3px-drag">3px solid #73AD21;</div>
			    <div style="clear:both"></div>
			    <div class="square-css" id="absolute-drag">absolute;</div>
			    <div style="clear:both"></div>
			    <div class="square-css" id="couriernew-drag">"Courier New"</div>
			    <div style="clear:both"></div>
			    <div class="square-css" id="inline-drag">inline-block;</div>
			    <div style="clear:both"></div>
			    <div class="square-css" id="lightblue-drag">lightblue;</div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			</div>
			<div style="float:left;">
			    <div class="squaredotted-css">body</div>
			    <div class="squaredotted-css">{</div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div class="squaredotted-css">background-color:</div>
			    <div class="squaredotted-css" id="lightblue-drop"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css">}</div>
			    <div class="squaredotted-css-blank"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css">p</div>
			    <div class="squaredotted-css">{</div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div class="squaredotted-css">font-family:</div>
			    <div class="squaredotted-css" id="couriernew-drop"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css">}</div>
			    <div class="squaredotted-css-blank"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css">ul</div>
			    <div class="squaredotted-css">{</div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div class="squaredotted-css">display:</div>
			    <div class="squaredotted-css" id="inline-drop"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css">}</div>
			    <div class="squaredotted-css-blank"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css">.right</div>
			    <div class="squaredotted-css">{</div>
			    <div class="squaredotted-css-blank"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div class="squaredotted-css">position:</div>
			    <div class="squaredotted-css" id="absolute-drop"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css-blank"></div>
			    <div class="squaredotted-css">border:</div>
			    <div class="squaredotted-css" id="3px-drop"></div>
			    <div style="clear:both"></div>
			    <div class="squaredotted-css">}</div>
			    <div class="squaredotted-css-blank"></div>
			    <div class="squaredotted-css-blank"></div>
			</div>
		</div>
	</div>
	<br><br>
	<button onclick="css1Submit()" class="btn btn-primary btn-lg">Submit</button>

</div> <!-- container -->

app/views/css/lesson1.html.erb
<div class="container" id="container-body">
	<div class="row">
		<div class="col-md-12">
			<h1>CSS - Lesson 1</h1>
			<p class="lead">Vivamus sagittis lacus vel augue laoreet rutrum faucibus.</p>

			<div class="modal" id="myModal">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
							<h4 class="modal-title">Success!</h4>
						</div>
						<div class="modal-body">
							<p>You are ready to go to the next level.</p>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Check your code</button>
							<button type="button" class="btn btn-success">Next Level</button>
						</div>
					</div>
				</div>
			</div>

			<div class="modal" id="myModal2">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
							<h4 class="modal-title">Fail!</h4>
						</div>
						<div class="modal-body">
							<p>You are not ready to go to the next level.</p>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-danger" data-dismiss="modal">Try Again</button>
						</div>
					</div>
				</div>
			</div>

			<div id="css-drag">
				<table id="table1">
					<colgroup>
						<col width="100"/>
						<col width="50"/>
						<col width="100"/>
						<col width="100"/>
						<col width="100"/>
						<col width="100"/>
						<col width="100"/>
					</colgroup>
					<tr>
						<td class="dark"><div class="css-drag">body</div></td>
						<td class="green_cell"><div class="css-drag">{</div></td>
						<td class="dark redips-single" title="Single content cell"><div class="css-drag"></div></td>
					</tr>
					<tr>
						<td class="dark"><div class="css-drag"></div></td>
						<td class="yellow_cell"><div class="css-drag">background-color:</div></td>
						<td id="lightblue-drop" class="dark redips-single" title="Single content cell"><div id="3px-drag" class="css-drag">3px solid #73AD21;</div></td>
					</tr>
					<tr>
						<td class="dark"><div class="css-drag">}</div></td>
						<td class="yellow_cell"><div class="css-drag"></div></td>
						<td class="dark redips-single" title="Single content cell"><div  class="css-drag"></div></td>
					</tr>
					<tr>
						<td class="dark"><div class="css-drag">p</div></td>
						<td class="dark redips-single" title="Single content cell"><div  class="css-drag">{</div></td>
						<td class="green_cell"><div class="css-drag"></div></td>
					</tr>
					<tr>
						<td class="dark"><div id="title1-drag" class="css-drag"></div></td>
						<td class="dark redips-single" title="Single content cell"><div  class="css-drag">font-family:</div></td>
						<td class="green_cell" id="timesnew-drop"><div id="absolute-drag" class="css-drag">absolute;</div></td>
					</tr>
					<tr>
						<td class="dark"><div class="css-drag">}</div></td>
						<td class="dark redips-single" title="Single content cell"></td>
						<td class="green_cell"></td>
						
					</tr>
					<tr>
						<td class="dark"><div class="css-drag">li</div></td>
						<td class="green_cell"><div class="css-drag">{</div></td>
						<td class="dark redips-single" title="Single content cell"></td>
						
					</tr>
					<tr>
						<td class="dark"><div class="css-drag"></div></td>
						<td class="orange_cell"><div class="css-drag">display:</div></td>
						<td class="dark redips-single" title="Single content cell" id="inline-drop"><div id="timesnew-drag" class="css-drag">"Times New Roman", Times, serif;</div></td>
					</tr>
					<tr>
						<td class="dark"><div class="css-drag">}</div></td>
						<td class="dark redips-single" title="Single content cell"></td>
						<td class="green_cell"></td>
					</tr>
					<tr>
						<td class="dark"><div class="css-drag">.right</div></td>
						<td class="dark redips-single" title="Single content cell"><div class="css-drag">{</div></td>
						<td class="green_cell"><div class="css-drag"></div></td>
					</tr>
					<tr>
						<td class="dark"><div class="css-drag"></div></td>
						<td class="dark redips-single" title="Single content cell"><div  class="css-drag">position:</div></td>
						<td class="green_cell" id="absolute-drop"><div id="inline-drag" class="css-drag">inline;</div></td>
						
					</tr>
					<tr>
						<td class="dark"><div class="css-drag"></div></td>
						<td class="orange_cell" id="body2-drop"><div class="css-drag">border:</div></td>
						<td class="dark redips-single" title="Single content cell" id="3px-drop"><div id="lightblue-drag" class="css-drag">lightblue;</div></td>
						
					</tr>
					<tr>
						<td class="dark"><div id="title-drag" class="css-drag">}</div></td>
						<td class="yellow_cell" id="html2-drop"></td>
						<td class="dark redips-single" title="Single content cell"></td>
						
					</tr>
					<!-- empty row -->
					<tr>
						<td colspan="7" class="redips-mark blank"></td>
					</tr>
					<!-- message row -->
					<tr>
						<td class="redips-mark blank"></td>
						<td class="redips-mark blank"></td>
						<td id="message" colspan="5" class="redips-mark dark2">Set css code respectively.</td>
					</tr>
				</table>
			</div>
		<button onclick="css1Submit()" class="btn btn-primary btn-lg">Submit</button>
		</div> <!-- col -->
	</div> <!-- row -->
</div> <!-- container -->

app/views/javascript/exercise1.html.erb
<div class="container" id="container-body">
	<div class="row">
		<div class="col-md-12">
			<h1>Javascript - Exercise 1</h1>
			<p class="lead">Rearrange the boxes of code to form a simple Javascipt if-else statement.</p>

			<div class="modal" id="myModal">
				<div class="modal-dialog">
					<div class="modal-content" id="welldone">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
							<h4 class="modal-title">Well done, <%= "#{@coder.first_name}" %>!</h4>
						</div>
						<div class="modal-body" id="welldonetext">
							<p>You are now ready to go to the next exercise!</p>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Check your code</button>
							<%= link_to "Next Exercise", ruby_exercise1_path, class: "btn btn-success" %>
						</div>
					</div>
				</div>
			</div>

			<div class="modal" id="myModal2">
				<div class="modal-dialog">
					<div class="modal-content" id="tryagain">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
							<h4 class="modal-title">Almost there, <%= "#{@coder.first_name}" %>!</h4>
						</div>
						<div class="modal-body">
							<p>Tip: A variable must be the first line in this exercise.</p>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-danger" data-dismiss="modal">Try Again</button>
						</div>
					</div>
				</div>
			</div>

			<ul id="sortable1" class="connectedSortable">
				<li class="ui-state-highlight" id="doc-math-drag">document.write("Math Book");</li>
				<li class="ui-state-highlight" id="if-history-drag">if (book == "history") {</li>
				<li class="ui-state-highlight" id="close-bracket-drag">}</li>
				<li class="ui-state-highlight" id="doc-history-drag">document.write("History Book");</li>
				<li class="ui-state-highlight" id="else-if-math-drag">else if (book == "math"){</li>
				<li class="ui-state-highlight" id="close-bracket-drag">}</li>
				<li class="ui-state-highlight" id="doc-unknown-drag">document.write("Unknown Book");</li>
				<li class="ui-state-highlight" id="var-drag">var book = "math";</li>
				<li class="ui-state-highlight" id="close-bracket-drag">}</li>
				<li class="ui-state-highlight" id="else-drag">else {</li>
			</ul>

		</div>
	</div>
	<div class="row"><br><br>
		<div class="col-md-12">
			<button onclick="js1Submit()" class="btn btn-primary btn-lg">Submit</button>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
	<p>&copy; 2016 GoGoCoder.com</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Go Go Coder", root_path, class: "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

			<ul class="nav navbar-nav navbar-right">
				
				<% if coder_signed_in? %>

		        	<li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">HTML <span class="caret"></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><%= link_to "Exercise 1", html_exercise1_path %></li>
			          </ul>
			        </li>

			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">CSS <span class="caret"></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><%= link_to "Exercise 1", css_exercise1_path %></li>
			          </ul>
			        </li>

			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Javascript <span class="caret"></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><%= link_to "Exercise 1", javascript_exercise1_path %></li>
			          </ul>
			        </li>

			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ruby <span class="caret"></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><%= link_to "Exercise 1", ruby_exercise1_path %></li>
			          </ul>
			        </li>

		        	<li><%= link_to "#{current_coder.first_name}'s Codes", codes_path %></li>
		        	<li><%= link_to "New Code", new_code_path %></li>
		        	<li><%= link_to "Edit Coder", edit_coder_registration_path %></li>
		        	<li><%= link_to "Sign Out", destroy_coder_session_path, method: :delete %></li>
		        <% else %>
		        	<li><%= link_to "Log In", new_coder_session_path %></li>
		        <% end %>

			</ul>
		</div>
	</div>
</nav>

app/views/welcome/welcome.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron" id="jumbo-welcome">
				<h1>Hi <%= "#{@coder.first_name}" %>!</h1>
				<p>What do you want to do today?</p>
				<p><a class="btn btn-info btn-lg">Choose An Exercise Below</a>&nbsp;&nbsp;&nbsp;<%= link_to "Create New Code", new_code_path, class: "btn btn-success btn-lg" %></p>
			</div>
		</div>
	</div>
	<div class="row" id="welcome-box-row">

		<div class="col-md-2" id="welcome-box">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">Level 1</h3>
				</div>
				<div class="panel-body">
					<%= link_to "HTML", html_exercise1_path, class: "btn btn-success" %>
				</div>
			</div>
		</div>

		<div class="col-md-2" id="welcome-box">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Level 2</h3>
				</div>
				<div class="panel-body">
					<%= link_to "CSS", css_exercise1_path, class: "btn btn-primary" %>
				</div>
			</div>
		</div>

		<div class="col-md-2" id="welcome-box">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">Level 3</h3>
				</div>
				<div class="panel-body">
					<%= link_to "Javascript", javascript_exercise1_path, class: "btn btn-info" %>
				</div>
			</div>
		</div>

		<div class="col-md-2" id="welcome-box">
			<div class="panel panel-warning">
				<div class="panel-heading">
					<h3 class="panel-title">Level 4</h3>
				</div>
				<div class="panel-body">
					<%= link_to "Ruby", ruby_exercise1_path, class: "btn btn-warning" %>
				</div>
			</div>
		</div>

		<div class="col-md-2" id="welcome-box">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title">Coming Soon!</h3>
				</div>
				<div class="panel-body">
					<%= link_to "Rails", welcome_path, class: "btn btn-danger" %>
				</div>
			</div>
		</div>
	</div>
</div>